apiVersion: v1
kind: Pod
metadata:
  name: toleration-test
spec:
  tolerations:
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - name: nginx
      image: nginx
